version: 1.2
workflows:
   - name: pgsc_calc
     subclass: WDL
     primaryDescriptorPath: /pgsc_calc.wdl
     testParameterFiles:
       - /pgsc_calc.json
   - name: pgsc_calc_prepare_genomes
     subclass: WDL
     primaryDescriptorPath: /pgsc_calc_prepare_genomes.wdl
     testParameterFiles:
       - /pgsc_calc_prepare_genomes.json
   - name: calc_scores
     subclass: WDL
     primaryDescriptorPath: /calc_scores.wdl
   - name: fit_ancestry_model
     subclass: WDL
     primaryDescriptorPath: /fit_ancestry_model.wdl
   - name: adjust_scores
     subclass: WDL
     primaryDescriptorPath: /adjust_scores.wdl
   - name: adjust_scores_empirical
     subclass: WDL
     primaryDescriptorPath: /adjust_scores_empirical.wdl
   - name: subset_score_file
     subclass: WDL
     primaryDescriptorPath: /subset_score_file.wdl
   - name: summarize_score_weights
     subclass: WDL
     primaryDescriptorPath: /summarize_score_weights.wdl
     